# Generated by Django 2.0.2 on 2019-02-06 23:59

import Jobpost.models
from django.db import migrations, models
import django_countries.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postedDate', models.DateTimeField(auto_now_add=True)),
                ('position', models.CharField(max_length=255)),
                ('companyName', models.CharField(max_length=255)),
                ('companyLogo', models.ImageField(blank=True, default='default.jpg', upload_to='')),
                ('companyEmail', models.EmailField(max_length=255)),
                ('companyApplyUrl', models.URLField()),
                ('jobResp', models.TextField()),
                ('jobDesc', models.TextField()),
                ('jobReq', models.TextField()),
                ('salary', models.IntegerField(blank=True)),
                ('location', django_countries.fields.CountryField(default='', max_length=746, multiple=True)),
                ('category', models.CharField(default='fulltime', max_length=50)),
                ('postExpire', models.DateTimeField(default=Jobpost.models.get_deadline)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
